title: Studying Moral-based Differences in the Framing of Political Tweets
description: >- # this means to ignore newlines until "baseurl:"
  ICWSM'21
# Build settings
remote_theme: socialcomplab/cayman
github:
  parent: https://socialcomplab.github.io/
